In [11]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.ensemble import *
data = pd.read_csv('./avocado.csv')

In [12]:
data.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [13]:
del data['Unnamed: 0']

In [14]:
data.value_counts()

Date        AveragePrice  Total Volume  4046       4225        4770     Total Bags  Small Bags  Large Bags  XLarge Bags  type          year  region
2018-03-25  2.09          20242.65      144.40     10949.63    0.00     9148.62     9137.73     10.89       0.00         organic       2018  HartfordSpringfield    1
2016-01-31  1.04          151247.03     76816.44   21968.91    256.10   52205.58    21691.82    30513.76    0.00         conventional  2016  Jacksonville           1
            1.01          312455.27     159088.93  88740.60    9166.73  55459.01    38452.05    17006.96    0.00         conventional  2016  SouthCarolina          1
            1.02          81433.73      9874.87    21594.16    80.34    49884.36    39705.53    10178.83    0.00         organic       2016  LosAngeles             1
                          1615465.33    18769.06   1284268.92  1383.65  311043.70   269851.19   41190.34    2.17         conventional  2016  NewYork                1
                                                                                                                                                                   ..
2017-02-26  1.25          307685.60     172780.16  46592.50    70.60    88242.34    53501.63    34737.38    3.33         conventional  2017  Orlando                1
            1.24          599178.18     11751.20   489161.87   5887.27  92377.84    88862.29    3515.55     0.00         conventional  2017  Boston                 1
            1.23          369337.81     209754.73  61504.60    54.62    98023.86    60609.67    37414.19    0.00         conventional  2017  Tampa                  1
                          30803.34      3411.42    5012.15     25.84    22353.93    516.54      21837.39    0.00         organic       2017  Portland               1
2015-01-04  0.65          1048062.16    770635.37  178418.32   6509.41  92499.06    92499.06    0.00        0.00         conventional  2015  PhoenixTucson          1
Length: 18249, dtype: int64

In [15]:
del data['4046']
del data['4225']
del data['4770']

In [16]:
data

,Date,AveragePrice,Total Volume,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...
18244,2018-02-04,1.63,17074.83,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,2018-01-28,1.71,13888.04,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,2018-01-21,1.87,13766.76,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,2018-01-14,1.93,16205.22,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,2018-01-07,1.62,17489.58,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [17]:
dates = []
for date in data['Date']:
    dates.append(date.replace('-',''))
data['Date'] = dates

In [18]:
data

,Date,AveragePrice,Total Volume,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,20151227,1.33,64236.62,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,20151220,1.35,54876.98,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,20151213,0.93,118220.22,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,20151206,1.08,78992.15,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,20151129,1.28,51039.60,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...
18244,20180204,1.63,17074.83,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,20180128,1.71,13888.04,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,20180121,1.87,13766.76,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,20180114,1.93,16205.22,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,20180107,1.62,17489.58,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [19]:
del data['Total Volume']
del data['Total Bags']
del data['Small Bags']
del data['Large Bags']
del data['XLarge Bags']

In [20]:
data

           Date  AveragePrice          type  year            region
0      20151227          1.33  conventional  2015            Albany
1      20151220          1.35  conventional  2015            Albany
2      20151213          0.93  conventional  2015            Albany
3      20151206          1.08  conventional  2015            Albany
4      20151129          1.28  conventional  2015            Albany
...         ...           ...           ...   ...               ...
18244  20180204          1.63       organic  2018  WestTexNewMexico
18245  20180128          1.71       organic  2018  WestTexNewMexico
18246  20180121          1.87       organic  2018  WestTexNewMexico
18247  20180114          1.93       organic  2018  WestTexNewMexico
18248  20180107          1.62       organic  2018  WestTexNewMexico

[18249 rows x 5 columns]

In [21]:
data.dtypes

Date             object
AveragePrice    float64
type             object
year              int64
region           object
dtype: object

In [22]:
def object_to_int(info,coloum):
    index = -1
    info_dict = {}
    for coloum_info in info[coloum]:
        if coloum_info not in info_dict:
            index = index + 1
            info_dict[coloum_info] = index
    all_dict = []
    for coloum_info in info[coloum]:
        all_dict.append(info_dict[coloum_info])
    return all_dict,info_dict

In [23]:
import json
with open('type_info_json.json','w') as json_file:
#     json.load(json_file)
    json.dump(object_to_int(data,'type')[1],json_file)
data['type'] = object_to_int(data,'type')[0]

In [24]:
!ls

'archive (24).zip'   main.ipynb   models		  type_info_json.json
 avocado.csv	     main.py	  region_info_json.json   wandb

In [25]:
data

           Date  AveragePrice  type  year            region
0      20151227          1.33     0  2015            Albany
1      20151220          1.35     0  2015            Albany
2      20151213          0.93     0  2015            Albany
3      20151206          1.08     0  2015            Albany
4      20151129          1.28     0  2015            Albany
...         ...           ...   ...   ...               ...
18244  20180204          1.63     1  2018  WestTexNewMexico
18245  20180128          1.71     1  2018  WestTexNewMexico
18246  20180121          1.87     1  2018  WestTexNewMexico
18247  20180114          1.93     1  2018  WestTexNewMexico
18248  20180107          1.62     1  2018  WestTexNewMexico

[18249 rows x 5 columns]

In [26]:
data.dtypes

Date             object
AveragePrice    float64
type              int64
year              int64
region           object
dtype: object

In [27]:
all_dates = []
for date in data['Date']:
    all_dates.append(int(date))

In [28]:
data['Date'] = all_dates

In [29]:
data

           Date  AveragePrice  type  year            region
0      20151227          1.33     0  2015            Albany
1      20151220          1.35     0  2015            Albany
2      20151213          0.93     0  2015            Albany
3      20151206          1.08     0  2015            Albany
4      20151129          1.28     0  2015            Albany
...         ...           ...   ...   ...               ...
18244  20180204          1.63     1  2018  WestTexNewMexico
18245  20180128          1.71     1  2018  WestTexNewMexico
18246  20180121          1.87     1  2018  WestTexNewMexico
18247  20180114          1.93     1  2018  WestTexNewMexico
18248  20180107          1.62     1  2018  WestTexNewMexico

[18249 rows x 5 columns]

In [30]:
data.dtypes

Date              int64
AveragePrice    float64
type              int64
year              int64
region           object
dtype: object

In [31]:
import json
with open('region_info_json.json','w') as json_file:
#     json.load(json_file)
    json.dump(object_to_int(data,'region')[1],json_file)
data['region'] = object_to_int(data,'region')[0]

In [32]:
data

           Date  AveragePrice  type  year  region
0      20151227          1.33     0  2015       0
1      20151220          1.35     0  2015       0
2      20151213          0.93     0  2015       0
3      20151206          1.08     0  2015       0
4      20151129          1.28     0  2015       0
...         ...           ...   ...   ...     ...
18244  20180204          1.63     1  2018      53
18245  20180128          1.71     1  2018      53
18246  20180121          1.87     1  2018      53
18247  20180114          1.93     1  2018      53
18248  20180107          1.62     1  2018      53

[18249 rows x 5 columns]

In [33]:
del data['year']

In [34]:
X = data.drop('AveragePrice',axis=1)
y = data['AveragePrice']

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [36]:
len(X_train),len(X_test)

(13686, 4563)

In [37]:
model_RandomForestClassifier = RandomForestClassifier()
model_RandomForestRegressor = RandomForestRegressor()

In [38]:
model_RandomForestRegressor.fit(X_train,y_train)

RandomForestRegressor()

In [39]:
X_train

           Date  type  region
15139  20170625     1       7
7347   20170430     0      32
15965  20171126     1      23
5476   20160904     0      51
3557   20160731     0      14
...         ...   ...     ...
1310   20151018     0      25
3189   20160828     0       7
1704   20150322     0      32
15714  20170820     1      18
10694  20151101     1      30

[13686 rows x 3 columns]

In [40]:
y_train

15139    1.99
7347     1.78
15965    1.63
5476     1.04
3557     1.60
         ...
1310     1.05
3189     1.40
1704     1.18
15714    1.57
10694    1.62
Name: AveragePrice, Length: 13686, dtype: float64

In [41]:
del model_RandomForestClassifier

In [42]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
model_RandomForestRegressor.score(X_test,y_test)

0.9551940836540024

In [43]:
# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
# grid = {
#     "n_estimators":[250,500,1000],
#     "max_depth":[None,12.5,25],
#     "max_features":["auto","sqrt",'log2'],
# #     "min_samples_split":[1],
# #     "min_samples_leaf":[1]
# }
# model_RandomForestRegressor_gs = RandomForestRegressor()
# gs_model = GridSearchCV(estimator=model_RandomForestRegressor_gs,verbose=5,cv=10,param_grid=grid)
# gs_model.fit(X_train,y_train)
# print(gs_model.best_estimator_)
# print(gs_model.score(X_test,y_test))

In [44]:
# import wandb
# wandb.login()
# wandb.init(project='Predicting-Avacado-Prices')
# wandb.sklearn.plot_regressor(model_RandomForestRegressor_gs, X_train, X_test, y_train, y_test,  model_name='RandomForrestRegressor-GS')
# wandb.sklearn.plot_learning_curve(model_RandomForestRegressor_gs, X, y)
# wandb.sklearn.plot_elbow_curve(model_RandomForestRegressor_gs, X_train)
# wandb.sklearn.plot_silhouette(model_RandomForestRegressor_gs, X_train, ['Price'])
# wandb.sklearn.plot_outlier_candidates(model_RandomForestRegressor_gs, X, y)
# wandb.sklearn.plot_residuals(model_RandomForestRegressor_gs, X, y)

In [45]:
import wandb
wandb.login()

wandb: Currently logged in as: ranugad (use `wandb login --relogin` to force relogin)

True

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
# grid = {
#     "n_estimators":[10,100,200,400,800,1600],
#     "max_depth":[None,5,10,20,30],
#     "max_features":["auto","sqrt",'log2'],
#     "min_samples_split":[2,4,6],
#     "min_samples_leaf":[1,2,4]
# }
# model_RandomForestRegressor_rs = RandomForestRegressor()
# rs_model = RandomizedSearchCV(estimator=model_RandomForestRegressor_rs,verbose=5,cv=10,param_distributions=grid,n_iter=25)
# rs_model.fit(X_train,y_train)
# print(rs_model.best_estimator_)
# print(rs_model.score(X_test,y_test))

In [47]:
# import wandb
# wandb.login()
# wandb.init(project='Predicting-Avacado-Prices')
# wandb.sklearn.plot_regressor(model_RandomForestRegressor_rs, X_train, X_test, y_train, y_test,  model_name='RandomForrestRegressor-RS')
# wandb.sklearn.plot_learning_curve(model_RandomForestRegressor_rs, X, y)
# wandb.sklearn.plot_elbow_curve(model_RandomForestRegressor_rs, X_train)
# wandb.sklearn.plot_silhouette(model_RandomForestRegressor_rs, X_train, ['Price'])
# wandb.sklearn.plot_outlier_candidates(model_RandomForestRegressor_rs, X, y)
# wandb.sklearn.plot_residuals(model_RandomForestRegressor_rs, X, y)

In [48]:
import pickle

In [49]:
pickle.dump(model_RandomForestRegressor_rs,open('model_RandomForestRegressor_rs.pkl','wb'))

NameError: name 'model_RandomForestRegressor_rs' is not defined

In [50]:
print('Done :)')

Done :)

In [51]:
# Random 1 = 0.8737513781045558
# Normal 1 = 0.8677359562635705
# Grid 1 = 0.8667642179459016

In [58]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
grid = {
    "n_estimators":[100,500,1000,10000],
    "max_depth":[2,4,5],
    "max_features":["auto","sqrt",'log2'],
    "min_samples_split":[2,4,5],
    "min_samples_leaf":[2,4,5]
}
model_RandomForestRegressor_rs = RandomForestRegressor()
rs_model = RandomizedSearchCV(estimator=model_RandomForestRegressor_rs,verbose=5,cv=round(7),param_distributions=grid,n_iter=75)
rs_model.fit(X_train,y_train)
print(rs_model.best_estimator_)
print(rs_model.score(X_test,y_test))
import wandb
wandb.login()
wandb.init(project='Predicting-Avacado-Prices-')
wandb.sklearn.plot_regressor(model_RandomForestRegressor_gs, X_train, X_test, y_train, y_test,  model_name='RandomForrestRegressor-GS')
wandb.sklearn.plot_learning_curve(model_RandomForestRegressor_gs, X, y)
wandb.sklearn.plot_elbow_curve(model_RandomForestRegressor_gs, X_train)
wandb.sklearn.plot_silhouette(model_RandomForestRegressor_gs, X_train, ['Price'])
wandb.sklearn.plot_outlier_candidates(model_RandomForestRegressor_gs, X, y)
wandb.sklearn.plot_residuals(model_RandomForestRegressor_gs, X, y)
result = cross_val_score(rs_model,X,y,cv=100)
print(result)

Fitting 7 folds for each of 75 candidates, totalling 525 fits
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.541, total=   3.3s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.3s remaining:    0.0s

[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.532, total=   3.6s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    6.8s remaining:    0.0s

[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.549, total=   3.3s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5

[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   10.1s remaining:    0.0s

[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.542, total=   3.4s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5

[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:   13.5s remaining:    0.0s

[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.547, total=   3.4s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.540, total=   3.9s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=2, max_features=sqrt, max_depth=5, score=0.542, total=   3.6s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.496, total=   3.2s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.493, total=   3.0s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.503, total=   3.1s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.501, total=   3.2s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.504, total=   3.5s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.495, total=   3.0s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=sqrt, max_depth=4, score=0.495, total=   3.0s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=log2, max_depth=4
[CV]  n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=log2, max_depth=4, score=0.497, total=   3.2s
[CV] n_estimators=1000, min_samples_split=4, min_samples_leaf=4, max_features=log2, max_depth=4

KeyboardInterrupt:

In [59]:
pickle.dump(model_RandomForestRegressor,open('model_RandomForestRegressor.pkl','wb'))

In [60]:
!ls

'archive (24).zip'   main.py			       region_info_json.json
 avocado.csv	     model_RandomForestRegressor.pkl   type_info_json.json
 main.ipynb	     models			       wandb